dist: trusty
sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-test
    - python: 3.4
      env: TOXENV=py34-test
    - python: 3.5
      env: TOXENV=py35-test
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.7
      env: TOXENV=py37-test
      dist: xenial
    - python: 3.8
      env: TOXENV=py38-test
      dist: xenial
    - python: 3.8
      env: TOXENV=py38-docs
      dist: xenial
    - python: 3.8
      env: TOXENV=py38-doctest
      dist: xenial

install:
  # Upgrade pip to avoid issues installing tox on Python 3.4:
  # https://github.com/pypa/setuptools/issues/951
  - pip install -U pip
  - pip install -U tox

script:
  - tox
