dist: trusty
sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-test
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=doctest

install:
  - pip install -U tox

script:
  - tox
