dist: trusty
sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26-test
    - python: 3.6
      env: TOXENV=py36-test
    - python: 3.6
      env: TOXENV=py36-docs
    - python: 3.6
      env: TOXENV=py36-doctest

install:
  - pip install -U tox

script:
  - tox
