environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python38"

install:
  - "%PYTHON%\\python.exe -m pip install tox pymongo"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py test"
